create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  zone text check (zone is null or zone in ('A', 'B', 'C')),
  severity text not null default 'info' check (severity in ('info', 'warning', 'critical')),
  message text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists events_created_at_idx
  on public.events (created_at desc);

create index if not exists events_type_zone_created_at_idx
  on public.events (event_type, zone, created_at desc);

alter table public.events enable row level security;
grant all on table public.events to service_role;
grant usage, select on sequence public.events_id_seq to service_role;