-- Run once in the Supabase SQL editor. This creates history without changing device_states.
create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  zone text not null check (zone in ('A', 'B', 'C')),
  temperatura_c double precision not null,
  humedad_pct double precision not null,
  humedad_suelo_pct double precision not null,
  iluminancia_lux double precision not null,
  co2_ppm double precision not null,
  ph double precision not null
);

create index if not exists measurements_zone_created_at_idx
  on public.measurements (zone, created_at desc);

alter table public.measurements enable row level security;